# Introduction

House prices can be modelled based on the structural characteristics of the house (e.g. age, size, building materials, floor level, etc.), their location (e.g. proximity to urban services, distance to Central Business District - CBD, accessibility, etc.), and the surrounding environment (e.g. neighbourhood services and socio-economic aspects of its inhabitants, leisure facilities, noise levels, etc.) (@Chen2008, @Gultekin2006). We will focus our study in the socio-economic aspects of the neighbourhood and, in particular, in the migration structure (e.g. migration pressure, ethnic groups, ...).

## Hedonic price model

The house prices can be defined by the following function (@Chen2008, @Gultekin2006).

$$P_i = f(H_i, L_i, N_i) + \epsilon $$

Where $f$ represents the functional function in the hedonic model, *P* is the price of the house *i*, and $H_i$, $L_i$ and $N_i$ are the vector of the structural characteristics, the location variables, and the neighbourhood characteristics of the house *i*, respectively. Finally, $\epsilon$ is the error term.

### House characteristics

We get the housing prices and the house properties from the Building and Dwelling Register ([BBR](https://teknik.bbr.dk/forside)). There dataset contains information about the building (e.g. building are and renovation year) and the residential unit (e.g. size, number of rooms, floor level, etc.). The data from residential units are unique for each dwelling. However, some building characteristics are shared by several dwellings. We therefore merge both dataset for getting a dataset in which each row represents only one dwelling. Furthermore, we focused our study in residential dwellings and thus we selected the following building types from the BBS dataset (i.e. *BYG_ANVEND_KODE*):

-   120 - Fritliggende enfamiliehus *(Detached single-family house)*;
-   121 - Sammenbygget enfamiliehus *(Combined single-family house)*;
-   122 - Fritliggende enfamiliehus i tæt-lav bebyggelse (*Detached single-family house in dense-low-rise buildings*);
-   130 - (UDFASES) Række-, kæde-, eller dobbelthus (lodret adskillelse mellem enhederne) *((PHASE OUT) Row, chain, or semi-detached house (vertical separation between the units))*;
-   131 - Række-, kæde- og klyngehus *(Row, chain and cluster housing)*;
-   132 - Dobbelthus *(Semi-detached house)*;
-   140 - Etagebolig-bygning, flerfamiliehus eller to-familiehus *(Multi-storey residential building, multi-family house or two-family house)*;
-   190 - Anden bygning til helårsbeboelse *(Second building for year-round living)*.

These building types were then aggregated in four categories:

-   Single-family house: 120, 121, and 122;
-   Row, chain, or semi-detached house: 130, 131, and 132;
-   Multi-storey residential building: 140;
-   Second building for year-round living: 190.

### Location characteristics

[OpenStreetMaps](https://cran.r-project.org/web/packages/osmdata/vignettes/osmdata.html) and [kortforsyningen](https://kortforsyningen.dk/) were used for getting the data about the urban services (e.g. public transport network, parks, ...). Then, the interaction between those services and the house was modelled by potential models (@Weber2000, @Gultekin2006), where the intensity of the interaction between the elements and the house is inversely proportional to the distance between them (@Giraud2020).

$$ p_i = \sum_{j = i}^{n} M_i \cdot f(d_{ij}) $$

Where $p_i$ is the potential of the housing unit, $M_j$ the mass of the service, and $f(d_{ij})$ the negative function of the distance between the dwelling *i* and the service *j*.

### Neighbourhood characteristics

We have used the smallest administrative area of Denmark (i.e. parish) for evaluating the influence of the neighbourhoog characteristics on housing prices \color{red}(Use also potential model here -\> e.g. locate the stock of migrant population on the centroid of each parish and get the interaction intensity in each house??)\color{black}. The following tables from the [Denmark Statistics](https://www.dst.dk/da) were used:

-   [SOGN10B: Disposable income for households by parish, price unit and income](https://betalingsdata.statistikbank.dk/statbank5a/SelectVarVal/Define.asp?MainTable=SOGN10B&PLanguage=0&PXSId=0&wsid=cflist).
-   [SOGN05: Population (end November) by parish, socioeconomic status and sex](https://betalingsdata.statistikbank.dk/statbank5a/SelectVarVal/Define.asp?MainTable=SOGN05&PLanguage=0&PXSId=0&wsid=cflist)
-   [SOGN07: Households disposal of vehicles by parish and use of cars](https://betalingsdata.statistikbank.dk/statbank5a/SelectVarVal/Define.asp?MainTable=SOGN07&PLanguage=0&PXSId=0&wsid=cflist) \color{red}(do you think it could be relevant? Do people think on parking issues when they buy a house?)\color{black}
-   [KMSTA003: Summary vital statistics by parish and movements](https://www.statbank.dk/statbank5a/SelectVarVal/Define.asp?MainTable=KMSTA003&PLanguage=1&PXSId=0&wsid=cftree)
-   [KMSTA001: Population 1. January by parish, ancestry and member of the National Church](https://www.statbank.dk/statbank5a/SelectVarVal/Define.asp?MainTable=KMSTA001&PLanguage=1&PXSId=0&wsid=cftree).
-   [VAN1AAR: Immigration (yearly) by municipality, sex, age, country of origin and citizenship](https://www.statbank.dk/statbank5a/SelectVarVal/Define.asp?MainTable=VAN1AAR&PLanguage=1&PXSId=0&wsid=cftree) \color{red}Can we also have this dataset at parish level?\color{black}
