# (PART) Population growth in Denmark and housing prices {-}

# Population growth, migration and house prices {#intro}

Migration and housing prices are closely related with profound implications on urban planning. In this sense, there is  a two-way causal relationship between migration and house prices (e.g. @Lin2018, @Jeanty2010). On the one hand, a rise on house prices will increase household’s housing equity and, therefore, homeowners would have a higher financial flexibility for purchasing a new house. On the other hand, high housing prices can make the house unaffordable. Prices differences between the region where migrants live and regions where they intend to move may also affect in- and out- migration rates. Finally, the expectation of future house prices also plays an important role in the decision to move (@Peng2019). Furthermore, migration increases the housing demand and, as a consequence, the prices (@Wang2017a). An example of this effect has been found in Sweden where “a 1% increase in the foreign-born population results in a 0.8% increase in house prices, which increases to 1.2% if internal migration is also accounted for” (@Tyrcha2019). 
We analyse therefore housing prices, population and migration patterns in Denmark, evaluating the influence of housing prices on migration (and vice versa). Specific questions we will respond are, among others:    

- How have housing prices changed over time in Denmark?  

- How does it affect mobility and the population of a region?  

- What is the effect of immigration on housing prices?  

- What is the percentage of immigrants that own/rent a property? 

- Is there racial segregation of immigrants? How does it affect mobility? 

Do the developments of housing prices in areas with significantly higher (or lower) representation of immigrants differ from the developments in nearby areas? If there is an effect, does it differ depending on the immigrants’ country of origin? 

